[launcher]
;; Regions: Korea, International, China
;; WARNING: Do not run a region setting that you are not using
;; the data/dongle for, or else it can corrupt your installation.
region=China
;; Data download methods: ftp, http
method=http

[override]
;; Advanced users only: Override the server, user or pass for the
;; conduct connection. Region setting usually takes care of this.
server=
user=
pass=
