@echo off
rem ============================================================
rem  DMT3 .pt Converter  --  DJMAX TECHNIKA 3 pattern decryptor
rem  Kimi K3 & AnderX
rem  License: CC BY-NC-SA 4.0 (see LICENSE.txt)
rem ============================================================
setlocal
set "DMT3_SELF=%~f0"
set "DMT3_RAWARGS=%*"
set "DMT3_WS=-WindowStyle Normal"
if "%~1"=="" set "DMT3_WS=-WindowStyle Hidden"
powershell -STA -NoProfile -ExecutionPolicy Bypass %DMT3_WS% -Command "$c=[IO.File]::ReadAllText($env:DMT3_SELF,[Text.Encoding]::UTF8); iex $c.Substring($c.LastIndexOf('#__PS_BEGIN__'))"
exit /b %ERRORLEVEL%
#__PS_BEGIN__
# DMT3 .pt 谱面转换器 — PowerShell 宿主段
# 用系统自带 .NET Framework 现场编译下面的 C# 源码并运行。
$ErrorActionPreference = 'Stop'
# 参数经由环境变量传入（保留引号），按引号切分还原：
$global:__cliArgs = @()
if ($env:DMT3_RAWARGS) {
    [regex]::Matches($env:DMT3_RAWARGS, '"[^"]*"|\S+') | ForEach-Object {
        $global:__cliArgs += $_.Value.Trim('"')
    }
}
$cs = @'
using System;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.IO;
using System.Windows.Forms;

// <auto-generated by gen_embedded.py> self-test vector for DMT3 pt converter
static partial class EmbeddedData {
    public const string PtTestRawB64 =
        "UFRGRgEAwAAAAAdDQAAAMAAA043jQisAU2HffJlZrRmRnOGlnahiXSVd7SPAALbzvNwbzysFQno1A71e5T1dN4u0LwZGXBdxrHZv" +
        "IyH/Bqj/jJSAlm1VbjFD7Qmq0ddu3CXBVSL14f+wg9wtleMT5CFKuHhh52UmaT/OvT+Gxa8npo7/kpE3WYKJTt1ejPjEsv3Z6Dxz" +
        "pu3Mg0KKuEcu+LZdg4lHKQ6XyWvEIOhVAOom14ExIKscoFnZ9e3p6BkAWsdOO0srXhTJiKFAXXd1HwBh1/0OIRbUmW1rELFP2HT3" +
        "RDxoCStkrQIhjaLPQUbZTigH2bAXpjVod8MVeuMp3s+qNanh22Y7sSnmpBOhTV0RpFxhaS8Oyq/s5DQp8NBcWmQxq3dSRNxmeCvj" +
        "EmOV27urvZ0N2p3QC6buuqNKMhV8XyzStDhppsLdmTapGoGyNrV5l6TNGC5MsUia085FVS4llmZTGqsihX3yvkcbfy8UhfUYhHT5" +
        "Tgd89hbWxlu7YrcPXW9M7qbCaYvXDZjh2W2KAgj9c5bKYNyyKp4EG9FMkZ0RXoowuL8SdIV84x78ya2Lr/jI2ktOWDvMrnsMA3E+" +
        "T9e9QTS2ocx9mHgX2po/ZjBhMyMtMXiRhTxJd6JdhUeYuVkRU+OqT0+1HRZy+9Z4DtRfeRXQUXfYSZzg8X2jX1y9BsuV4cfcA4ap" +
        "5DaQUe0BC8a+mD+6tgWjlvU7dxR7tVnlfw8MPMT3Z3NLegTtYMR59afF9p7COfNpPp9naK08FrFX38f1+BE3vRthHlsfjekFSuNE" +
        "d+RKFgKkKb2Na4U23sY4fcosriLkT5oMlQ2BYPlmUKFE2urIHj9iZsUgnK+t36f8zc0r8fI5r6jF4tR6DzC4wDz84qbXWZ7VZzfo" +
        "YqNI33+fFAspstGdAeDw3rT5T/UUwcCzYSifMD6rAMCR0M7mjWpDpaulHbVs+fenyrA2lRLkkh9JTtExKK6lO1Uk9E9eWV+Ekk8R" +
        "8ir/KD9vIyy1rgJm3CFd3E5D2fhUOeMB5x104EKJbvAr2z8KEOScdg9xWXMjhYKMK9y+5vQ5rq065TZs2RTm8y9B8fz8uBzDSQmf" +
        "GubFWuCXScZT8Y3bL8QIuxkgtIU9PFE4Sba+2tYH0d6UEZxIK7bux70oc0jgpOsRVfs4DvP99ovwXSq5PjngwBjoQH1U2/C6PYdN" +
        "CFQVt10GC2xnDR8/fM3QS294EFnESM3x0hxQjZRuSPaRbje/rEjMiUTvLxqkKuvwkyo0l8JhyxbUF+pjK4xHpiXDZEF+FNMMOSoZ" +
        "oIwpxBBjqQ2jbyOp9FpCLIjqXGGTzB7TXWzAsNIOx20mAutXDc8J40IEIPGgRn+gbr16quQyEhrt4in0GhP5f2d3decL1vV/CrqJ" +
        "qqkWr/rKGgfezuFXVnF4Fo3u8XHIdEqEdi987JX3W50oLLNdGaa1WJWZrlKaU9oga1MPMMkxttt8I6iEKqv/vwt2d9O+QSl+ZACH" +
        "iTrV90EhNCm1pH2se+GPTVDN+THnVjqP76iPv6EqTN4TGaiMSfTfJh3OlYh1v48AUg4Gy9JSk7CQzyjzFlTfiabnkYJy8978YUSt" +
        "+9sJKucuL6GWrJ8feCP/oe7oXqDV/1KZqdFzyrhdwgtH+vqCe2BnWkDr/Pyoztx/uSI95s/cnw+nPRe+4+8J75zdfyLuQjYjaLV6" +
        "5tsJbQTnmMMoElhf0D4o3hM3IZcFWPXLulNPIufqk8BmjiMdMulkYwKuwIJihb8gd73FMhoGTnENSYtMFzxsDZ0q7p+BvNUSKKe3" +
        "nUYD6e2eSqfYdv4m9sviRmaF9X8ttOSZReJm60E/IiUhWiB1Za4tizqwU9kBrTpYCgKxARIaWXBgp79o0u9hodYnuLGz7XSlY0E6" +
        "MRh/brg0kovbVBjUIFhXOfXNz8wTeAGqJRolFijnKQJIRJfqyxsCYD5VD5LSBwHJWaH9SQZB7SrONzgdNkjRQ5DzgoKyoaVIK0O6" +
        "we3uaIMRDP4mfIxg4sWMMrOpJIKDXsocYDw3KSdvtco/clPS0rS5CWMDI/CvL3n+uPXl3ifXJCZ44ygFADFKkY5JW1PqmLiAClGG" +
        "92Nzhf4S9NbTVu+0Z6ElwaNvhmelBYf8zeFUvgoiqxYwA/qkzRUxt9EHw2AuqM2r8Jwc8Lwjd24XY7TqyORooGDEFo3A1zOQkSSQ" +
        "RIMOzFHH0r74WsaVJpHDE6eaABWpdOO8VS0oYFT1rTFx2A269iADWbITCKQu5kv1pDa/v4YW8KpwR3Y0eAg1NIrFIpyVnkrXQdxa" +
        "mUB4zaPZ+bHGJz8M9qId7PHbZ8inLKMdbRJcUSnrOjWOij/Fa1f7zNZ6bry8BFmeOCcM9kpJzYAFw0hAYnBIpgIJGpB63UhUiHlW" +
        "i878IfHt1poBeWxHEXarlg9mgg/gzOpbM1rbm0ZbT3yamGD7vShmiACivkw/SyE5oR0aqPwZI6x1X4aYdsNGZV80DcB0+m8HPa8w" +
        "wOLeBZkWV9MzUM7U4FOQTe03mA1tLI31CNAw10aomkc/NsPNMj/L87achTv14zBSTJ3hWT0mxRpi3xX9drPAzIN5w2pKWLVrhnTR" +
        "aBzFaD6qTth3gd3A1y87fC0ks49INigJ/WwdgIBiaISw+4cipH1U6Q5WWbqp6+bpZqA6krN8M6jUj2oq7o+AvJGYeOG0Z4acl3fs" +
        "w5Wqq4cVWM5NXiFPV7OjYNTwNEVvvy+JW6dJydvTFOlD+3S6Fky+bROVRkLDVulzmUgTJ9sHmt7y6/yJDqgKg8Bxa8tTuaxZKCye" +
        "wh0ZjuQR2oA0fxvlQqNIU7AqciagHTEkcz1GBI5FgDlJmms6wmOubwV8f1AXWc8amKAqKbQAIpJHWOQJ4WpvqPh3L8NjC04HQVG+" +
        "8BXygt1K98ThutdYpSGOBYug2byAkc2771n7gd+g8spzTOfQd/10mhEzD3IbLl1T8tNw/b1BEpkiEsNm0XuDKbCLPgvI8pYgr9Ui" +
        "nO4p8+Ziv3A1Vp0ZypG1X8MAlEuFJhYbtuv8fihVNIQOm6CbquTuR0G/XFUckPOPMyTmzcs7jzEDn5clpw2B0B3/o2jRrbqXaaF0" +
        "o7ByUnG+dpWT1cwHSQjjXtcmyiWFO7EYe2uG0Ze3MfYqAyQzNxp9y3mtaENXe7dvyVuL9YHyBf4rfY/SniWLCp6rH3/BwIC4Rj/p" +
        "vRr0PZMDYfEjfH39pdYXIjwgTfdNpNrEFVzjhdkXOqGUV4naOLw1uETTw15WncsQBBlcfLVhFoOfPpL51P6k0jmFDKL/TqV0vdZ9" +
        "M4EK5XXo0vKtwJeTK+SmKJ/t5Z/xn7owxWRZcAQYqiKWkjJ9vkhTY4EWI9Z1E/HIfQVkb1+l/cf9vd3DDwv1n7teKPbaEYHsZWP1" +
        "rN/sKsiF2z5FXXQiyi9MMLMtncRjZr1DYvhzhDb3gRIx1VENhJvVdraMmFDsz/k60TugiUnFUYRMHGMJBSpOCLz7lUm6wu1U9k2g" +
        "AXzx07jD12PLL111vHGykDPB3cvp7Z+GCBhYYvaxcDlqRcE4imJijr/bgx4keZo4qNbfZZve9dKHU3IeiKkY49KTp/fxK/XIREQW" +
        "Ajocc59z0en8+tABapzpPVN3n0lQWg3P4o6zQordC1J97sv8dCcEbL1PMjab5jd3iZkmEccUtTz+XvPEMCEiibqvFHSEEKDVTxTG" +
        "Vzv5WXx+9xhi4zw79S/aUPYD0hksKAtQb7gunTFVOGDj8bwUYTrHzhhynVU4P6XCbBYYifeBx5lKgP6/f/56kksjPe9zDhu111m3" +
        "O+RnzMA5cNkLGmnKaJn7fL4KmRWywWzKhhBzuXcQaebDmffxaGVPVSYJE91+TDrJ02ooBdVm5WnXCekb8Ee8WGPNcgkkLg72lsyk" +
        "JmGXyCoKN52m+S/2gHlAkoPdQCRTETQqkMdl0UhnjEJb2mL/MAd6zJvkinlkhXpDIeZPSjl5PfUjawB11bFz7jHNqsEBmNiUfRmY" +
        "+6HPcdcIU8q93UuzC8YGiQZgHJ+OqzrQOjbsZIRPxFtiHhvvSXHHo4euQDoFa7ezT8x8oOgOr/pbz/qFPtvQniVeqEfcoAFTJU1E" +
        "nF9H8j8NFPaysJEQCB+66cEO8gYtSfgk1Jpr9jCiFQBDvJChUR6FQiWjtw7/wzCmmlaVZY22RwcxwsKSJwmWV33EgWCy2uo+u8oD" +
        "Rxwdl4I1fyEXp3hLzT1icBeu73lldv/62/u263o1x1iziXAnntopG8xs1bEuFprq9hwENbDDNPomtToiCIh5R425hCWqvHq/4gWD" +
        "l8/scl0wlTkZnuRmHn/m4+4r+QqnqlipdaTpa7JjdnHC4oBlPohB+60b++wYnOX8BUjgLSOoFC/MLOyiDmn6yhzEd424rv5+Iqqx" +
        "IrhTJIruzj3I3LxOww1/DUd4V1Ir/KlgPAXLCZKK5XSIlugx4h3inAA5dp3Vg9ksg764IKf+wKoh2p4jjk2p9eLMH+SeaKuiKbF4" +
        "Nc6Osh8ENpxOOllgFBfyvi6Ss0bTiokkFkywPPLu06wvpIFwNWkHnvgt7Io+LzcA3IZTkYsTl9aVaCii4omD3OKwo5J4d2mKvgth" +
        "Ja4aXxIQA5v24kLuHc5a8OWqfwoW5ZKdgX+NWx8o4/MmQwNahBYZihZDBhRAgzKLPVsy0FCgAKkyxCJRQSJkwCEwQjWtDIdOQzAK" +
        "DmYuWnaqFMjQvvavKr1PpJfA8acv7DwH4Kn2UyGQsNXO3Jk2pK2buYlIRhdsOwU/YJT/M7d/TpTp4D+6AvypccjgsxF0kBzap1A1" +
        "bQ/Nn19MRHv9+R6ZEMJbhsEen+/k42cPFUVKsaibgu+7BEIJoKzRrKYvGV0Lq9WmRuLZmbI7NVglYJEnd548HAssvFO84GBmKQES" +
        "lZT5E0q26c7Lp1r53RPyZ3xvusnhWYYIFvjrucOVoh9KYLrbMSQ5ZEyp0HuU7FLYkIloUfU4IpqdiTSxB443jJLI1zXJak+Ijk8W" +
        "qP+jWH8WkracQb6TEmO97o9Iq21Fo9ITmICXnMAkSH3U0pBGcutOdh4OQOi52Aic8s5o7l6TW80+8HTZRxk2Ox2wzakh41O0Pvog" +
        "5+v0JH7CJhCaYVsAJm4gWxJBln8xGAFofJ1+w7ojcGSVVSdeMjxDy3/Pb1Tr3sU0feI4b+9eCbvCETkkbcPS2YfZmOwLzUgoOeDb" +
        "WzGjfv2yRZYqY870Ocwf+rkpdzDUjQVXlp49BURhXs6II6LcxJadGSrBDAbaishgBs9gLvoU/Fq/Tm/nVnJxdUmQgiKhUXnHXuCj" +
        "WRqdvch93Uav9SZvRBJFeBFaaJvt7CMpWoui+MfA/WY9gr3DcYtqaa6azgq1XZqo2pLlZBVjeAO1lX6BFlxmWBoRJ4HjHTKKSt9G" +
        "1qilAV8XbwjwXE40oWWTkzBY0SE09qy+g+GuaHzBsBODw8EQpyOX+1b1Gh1K5KZ/qi58BGhkjkTZsjP5qJOBj9sPspxQpbYlXQE/" +
        "fTUxpRCX/eyoCNaw6o7g8VFUvFus4eNKD3GdKXqo/RbxEUBUUOLRmWtlFNIVApbDLAY4nV6cDLztAOQv+aKrDxwYYWtKFYXHx+Z1" +
        "MHhzUp7IZoAdg1D9+yr08D8eD+kJS6VufSBJg0FVGyBEDe659Ssygfgc/HMLLwkOEOlY+pUldOZ5z4/1OQTysbk6nTaQQHd0hghm" +
        "aQmzCiLfVy9Jt2EZoWd9fwZZ3wB50WsilDNYk5tGkfhsTLWDdW9KBDXr7ZbHLRJEFTOlIqzT2YVhIPzJQb16jFvjJmRJlLzGqkl6" +
        "GRpNHPA/TEKjw+tH4yVGKXKVtV2L3qyMqOj6jCSR0RghvqQckVGQJIAtCkgHyenVMl3vuBMJnn1TPACO0Z+LIET5/e6cjlS+QgQV" +
        "1dd6Pza2zcgMKkP0LXbprWlO4knKgUcLCDNgGG25J16uFlCR1jR3JoGpJ/pyanMpOZiPPkzbhypaRG9Yz7ePW2bGai8GausANGs6" +
        "AbbCCm3Q9Oa86BmYk0PMmlzz4x9OxT/RzFPYLBSuIabgdGsvr/SOApgxSwTQcnCBCo/WHPgdJ4odHwwFk/cUDlGDMruqWy/lKRzm" +
        "HHHPXMPqNP3dr1lk8upc/zDi9HeiIS1Ap9Mbw73x49gZk125U0IZzfcih2nzFwE5o810q6hcCxd6HnhkbqaOeHB9TMaR0eDxJJJ0" +
        "RHGeYdJ03mP5oGpzRrQpNMsCesvtAcy/RMv+SQFO+AiSI+aEREp5fwrjVFRo+AqwAsGSxJV74Gu5HUGnoFo3ihG2j0PqzRM7Z4Mc" +
        "f8M1p01ICrlKmuwm5HhBmLdYR4SROyFWc+wJl+3x+hfu0XdufETVXHV7fAZprXMAGM6qyi7fD9f0QIXSL5/sCcfRFYfxGX+nansj" +
        "8Sy1bqbT0895Vo4ylRz4iNDkPTo8X8fZuFCSFW0A0bD7Y5ENEc4jlwKGq699+rtWr2jK9ZFH12nDWkpTWHw3+hmuX73MhaxzQHiN" +
        "7iCZr0sw4QF3NostCjAYNXD/xHROfpSjeYoU9TE0JGnYjJQBIe92GnvN3I6q+HXdXrW4iVSHGHeiQBtNy7OwYVKClP5RC/7xm3sG" +
        "jRG5wsj9LEY+Ey30J19JpuXIBwE1Vuk2Tps9vh4Y+uFHIVls4/Wb9z0ut8QVDtp+s5B3d59jwIYUIMg6La7zJgT4QPJZJQypvNOk" +
        "fKsyiEGZ81p9FtCnvI+NALcbydBEu7COsjNbiCLvbB+fKzB0yn30T5H3R3sPNTfNnBLGKK5HEZMeWJ/1tayxBQ4FDpijmUq7kKls" +
        "LCAIiHzbODwak8IL251Q1A3rZlfmUiGpLvDgoLlT7+/YD6t6B25qeB9tpxeiEhmfIedCJFaEpSr5DRXDjKwAesUwVd2bTQ0gNziV" +
        "9q+JWdvvhjUBlc45axZK1IcZRUxzWDU2FMtgt2k+fxIhUJSTahfQl9J/nhfYvN6ZdbnU43wmpSraWhEbcv2znEzOEl202yomuI+F" +
        "KX6UNuBwzXGq/wDe6SV6aMXAqdQErfv23iION0BZxCXuR0sR3s497jhsyEAXoGDK709H7TmWdnvfas97J8hRx+xNowmnT8uhaetP" +
        "n6J/vRK7LOhG5Uj+rAS2Mh1klCM6r/BlNxusAbhtLdqup/FkPH/HlgKXZXb7imP4Iq025GeBs/Gfbe6XS1M230+JTlV+jnsMgSYc" +
        "e8j3QHYDg/xbzuzCS946yVWW2cLqnhxjds4OqBqcgmTNtsjnoDjE9jeB49TChED9ZHK7zQ3fdxmznLu8EhCbBMoUP9Wsq4oWKxwj" +
        "t8QpAkc4C2q5G6/C3N5PVZ94BqN57DdMcdw+IG6YUb2pLOms2xtvUOlxAtd4C5tblY0obJvNwWD9qC98m/dldaKgrAZgB4+IU8zD" +
        "YVLI/EdZ1D7RoLBVXzeFE1BHM4Gj93wKBReBlGEZvVqIGJ3JXArAxjHaQIzatklqrDdEnxewkAs/b6FJUe2wVB2gKwoJTEaksePB" +
        "5Cn/f9avzM6onccCFRFV/VYeBJBZlNZLg/Dfbufgi4sU5yGl0P8SHc+ElHyRWVjBvzEPUZ/p4sqTl7IwnLdDI2dw6QqDIKxPYvA5" +
        "398iwNrTlAWBynQXKfqLrOZPeZZwS+TSceYpooDPbWVamx/DSt5aRvkMexEa3NukHWB7shgQKD/SqC/M4ghtzoBfOTivC6vG4+U5" +
        "GqrgGL4lq7APHcar87+H66IfXtV4ApMlSeL0Ll2SHLkonppNtV37lKV/otvmv0PR9KPqTy7RlBR9DIGmWK9X9c3VRqT57rJDNUfg" +
        "sj3YBWwCOqIamE9vA0o3op3Xz5rCVXyJF0XErRkOBAOlUrEi0PlaDWTB0RnMj4XLfiVZsyy+7BssOXRXlb/4r9w14/iavWb8cYXH" +
        "iINE9b/GdTADaM/mGvBAKDpvg9OPKVECa0LgC1jOtdcuX2jzjD28ow4IcGc8SVmnCQpeLAkpziU3K0XPC+6cuJ3s5KUB56jVcK8N" +
        "XlbAErmQ5pt1gCJZyYXGA8Pm8LNYBWOYcH7Gi8UTsF/M/W54Bmd9CFHhYXsaScW8r4MxxNQ9s6Q8N4d24D+3gv46U+YdtdtlnoeT" +
        "OkZuQzVs5P8rEqVaYTLCOH5Zy0ngK24OW79lSZtYcXqK8ye6cZQOgXvHLN//ck13eSpuAfiGgdF7NayJY70XWeAtYRmvZxaYcwK1" +
        "qx+Kr9Bbgi47CoqS14IMpN90p7VEZgEFiNNeFnZ90E6otco/z8nz3RJMk2EWIcQzBH4yaEmuB/8pzTQUl4EfeDaarwOq6NX32aU4" +
        "DiRXUkHSRPiRuEBnwoJq5ousHZ+4tSuBOcqcS1VyDQQNGL4oncTLkM1PmoVYxQAN8NCHLhBFDuFjHWeNrU19ohFth+4TpyE/AiCl" +
        "pJeuefbrbbnroga0kslBktBYRibdPoTj70mHEDED8PwCnnUCJKQu49i2UzDt4BkJUlh2Z4C+fFgsW1mHi1Z0yOJSVs+AM99pYTCm" +
        "/PaBX8s7/iAXzGxGs0M6NsleosCsjNE9L0S3qKdpQTv2/uvEByVG3H/5Ntiv7Ff3vC2aoAzR5AIOIXpQtarfoTHIZb7i3ksqlFe/" +
        "O6Z+J5je0Q3+9MY7RbsUkdV20Z0UgrpbqjOJKcW21vX8hJjTKfqjyV5ymGDTx0d+SRGn1kIdbUAygdyNtm4J3ALPgyDyUpZcJlrb" +
        "WIxYCxzlW+y2Y/8vNpRluwGYAMkjnrgI9vFCqVilClqA1wc6EWHnfqJxdwCFhOW98p16l0wPK+Otg4ANUDPzSejLYqpJt9ApZPac" +
        "B1ovKi1nYEawxP0//5xIJx+fc1N73uhfo2Jl2nApLWYEXl2fpPdd4opFutAPCNI0l73ThwsvXULmYCGKKAvyK96vIAW5IBDKHCAT" +
        "2C5N2NxHoMwrkuFBZt+vx/SQHJz4I2gmnDxnZhYoAQxEeVkeQTA8S5G7iA6vxMWuSgfQnVR5DOiS9ceGnc+fyig4VbJP82dluuo1" +
        "SEjnxGfOEm4WiSPpND57vh3esqie7+6wK7hPWNG3gIXkGVUR+uMKimhmtXO5rBtnhW4Tag5iQJpHoK/c2oJnK8l4iu+VtSskD0jK" +
        "+6MD7kjbI681bSScpJW7bZ6+ZKnJ+STgiQeCLVaT/iktup6i2iu/UZ7MTxjX/w6GIKhb9O/0pVZTxNoLzXtK26MPjK3m40RkwAer" +
        "7WlW3H6bTaCSSDOlKTOiP/G1NdUvEU5bFhv0ZtEhuxuSeQNk4EDlhu3U8YDg8YJBLGgaBuIEVolfJHpuuHaNijVFWvj76EyZFTVC" +
        "l07EM0Xiwv/qkSJgOLEzr0YQD3qSD0AY0KICRX5xWeGHOd6QJZu8KyttUb9BDLRIjvEWQt0N0X3moOsNY0yRATA9H9LUmLxyU2Xm" +
        "E8s3NEu9ei+Ab4XMmNWxuV5gOEq99sNrUhnZu+I/GRu66D7WzmgsHi6YVjlM6K3TaZ9zHWBrEU6Wu1cJcCRcaPYBESTaLfA+PXa3" +
        "YvoCAtB0lzFdeLoZHdB9WuZOZgBhJ2vFD+X8/e+pauXT7pE/0BdzQ4nrDqqZFoPeYtW/W+2vMpoXtuXlbAosqR2AbF2KECH89tbE" +
        "6gq8TDloNMk26Tdpazcl0R21yv3/mU4sP/YMygezHjtjSvQ3xLcB0g5NLWL+dWzffqdCwHspI7hHELkz3CJWjXOMyPi500iB3fvF" +
        "wrkdWBakSSFXh+3eUEhcTbiPrFkzqJReV4Rd7T4FVe48jRnhvTjz4KXBF/fs3yrqsKWRLfow0yaRS40LWH/xZlk1wWcsFMNxAoVD" +
        "CKU/6vPUZVxMGX67/1XA0571oypwUiezPVqyaCQs57eZjDAYff6wXqXwvWKzs/3JC3vMkwYSF0GpfV2i1vN6uzKTMpQC3mQTpzR2" +
        "7woGsoAQcqBa8vDlENmSIzOjvdytkiJFumtZm83aRFh2WPvXDZlKbghIwUi8xAw5G1E//3+jG+lceSx734XUDOX4KNYAS/sTPrD7" +
        "bQMazSTGAibxFYpZDHFBt32JC/8VWR3rxM1u5AcFnFsFJDKqK+xiSL4GU8fnc/aNhgpYITNLWlLW1Xl9jnD3+mrusDDU5i1pP4yd" +
        "eNN3Q8sSxN8cFMWC2+qxqUFQpFNDpCByLmYO6ZZ6Z4QGrLN3Ss/MzMHmJfrxbisvTCer2Xu9CLEpBlgFj3uAvJNNtGAuveQNFBGl" +
        "UJTknWK6Wd/GHZjb314jHEwolkTBmilK59wkLnkWSfRpQQdPq12HPWCn040FbGKY6a2gFoFIXNNqFS4YKITdUifoxq+hYKEWXj/F" +
        "Lkge9ybqZStMESZeM418cM4fqUDz8q/QV9QMHpUNu+zBIIFRcKCvMyUwjOmibyT7Gb98hHlzKBiAzORUnrXxvp2bvhSdmMYvTd7R" +
        "o7nc8y2ppH0ZMqTrrIeahg3yLQhN5W1+8h+lsQ8swbz9n8YyEC3y3ytieptfhnweyBpWbNqbi5+K89sE7c8lxS6DK3YTLKwK73V7" +
        "WF2u55ic9pqP4eN1MDYRltU5xMfeiR5109lkFzFfuhLhUsNtRa71R3qAG7hr/rPXAjUdyvHjTA3wQD0cDmeRiztUmXXoaQR4cwhm" +
        "argxWtArhiEzvRw+9wT07OMG/AtGRbCz6MXTpGEC95WIDEsSujYhlCzRrmOqq0mJfa+pL8mR7nTfXVuWcI7Kvg5O/EWQGIoE5mju" +
        "+xHert8hCire4s1Hm/X574Nst7Kk6n7BWGinQcIQPjlefclfk8ZwKAjHlfl8VIUw2sSszYZ/vZxqN4wcGcmmTXteq6mJG7OeQo4L" +
        "QDsGen41nbfOjSH0vSTVC91yXEK0eF6O08Puq48K6d3VLwyB2X9LjIpWNxS5qReCZNkNqrvcIjo9EKIUphs+Uoq6DX7se26BBm7Q" +
        "R1l7TL88sTt27Dw0UfeaTff9sq1Og1Eigm+5uUju2jBGm+8c1gDglMdnmJyhdtwSfAiLYJuF3ydcTeFX4VsC8svHY0qCvhq+u7BG" +
        "FQLXMeG3cTM+Suv0McVw1WkAsd1xnRv/4BIIhDjiFlT7okFHtM0MN0Asi8wjYTFyEt3EOkCv3xXuAGNI4dufJ/TLfWNZR9Ny/sgD" +
        "NsAUGNac323HGH3TgK8P6VBfT/jAAgCLrUhlrQI363crjj5MFE23loY2EVGb6dmiPaYLxCr8UlGesbzrKI39tOH0/dnMV2nj70VJ" +
        "u368p6jIAzuGBa1krgxtJrLs3o+G1lLmkCJs29eitGvr2mKkEd28xjwIUdeyl7u+wb4QlquIU9Er/eDKYQBTtqIEGskmnn9sh1TX" +
        "ycr9TuAjgOSwcA+rdMtI8msQvujsRS4o62F9hREKu4vgt1fJ3Fg83KSSy4p9soaxk9SDzqPZz88XKgGQzrogrH50q5DDsugw9Peb" +
        "EjfOd25p9TsRaA4lysvjBCKioeLundKOnnJViIIiPC9iyV7qLTnpGeL9Y4SJ7EfH+0fTMCYtrj8XiLNd0E7x6mjnkdve+0B50EbW" +
        "dTInCl3XJCO1hLuC99iLy+wo9KSgPoznRUM7eWdeHEkZ5p1OWXUzVcK2H97/rK31Sg7UiyvysWojyR6BhMgxyAJrrE6+97sgMcWY" +
        "LI34xh8iFhvRzrvd0lkMwVNzgzr7iDd+DrXGp8SiT2STlLOG2KRtS2UxP3zPHJRvkVbaErBuY5+lj/+wAtkLxgKHrz9UqKBxvOT+" +
        "p/anrwwWEujieBnw62zFUDCBPMDrQhpoTatkewomWk5+LuIQDWzJFICehxPSu1j4FTAPYrgxqOkObL26STjdJ9bVsON5hDWa/2hR" +
        "AgZ8PklHZxC4Cm6JvMSuERDFKdyIN3+9tqWDI5vR6rvbW6kgNQx6pS4WVr8vZzoHqir2ZbY6fV+jVru/PpZOlioOayQ2wwg+n9xR" +
        "3B5tFmHHyk6bbK+yPo1RI+F6Xd11LAciRxsRLnulFe/qVYE5M+tks8P3IsDw3D1sNfB1GtR7Nfwqi6CPIU9txM1lexkAbT0PoCed" +
        "ZovNhyd3IZSFQH5OIRAWxEPlxMVU9+2kjJbugvD1RxYdJh0Pu3vXoqWKvmFLogcFT4BfMxvFbL2t0Z2qByF0bsiMC5NP1Bw4sxu1" +
        "pwBBY0+f6BVwjHP2CNwrupjHVoBx8r25QU4jwIE/k8XLGbbslpWR3waJLrGLLtObEi3eCUeNocEHJIHs/gtiL9gOgjcq1D/nuOZR" +
        "3K50daoNeyKsaalGxWZHMcUioqcjgxPdYSi9sXhYxKGFRyK8yX2zC9Jf6rnP5yqVgu/d6isYYgit948BfaDzRlRiOWUr8zyklgwy" +
        "TaMH4L52/BDW/equOk0TwnnNDpPGutahmQh4Sj49ddp179OYvfN2wmiHfvjiwoAVcjkjqomNe1OAbDBR46tWkZ/3gnXc8wJ253g2" +
        "enD7QFstelw1ElphU9q+WnAUsMA9WtdcypwAYYLgIJaVZF+nnafgPszAxDyaNVDL5gcKjso+KxYqrGYerHdIexiqW6/TZXci753/" +
        "38xjfZv4OA3z1nw3l9f7LB5K0KOZIPYHZVSY7d7j2okhRg0VHp1PshpaxPt2JL1B4shi+I+5P/SeVVmVuf/79BnqU001dNusyRuX" +
        "FTZ24Pwyw195BV3Aj6Di6xhKah8ivpuX3QRq40XT3753r8JtqS7PnJyBrsHzGxmqT7zleG0u0mUQmxcYqU52GxUIQuRYx0HuvMAZ" +
        "gT8dDVCj3r0RNRYUFA4WMabht0o5MfzK5BMyH+gR+x3HZwx/mYJQwUTtVoIvk7iAwRJ2VsqRF7GtHlfpi9WXIbnu03M+76n0o3vO" +
        "yquT/N6uCxvOcH2kFv6kBM7C39FCFTkPwkwTIzs69ayzMEtLF4CobNs16+ObI1Ak/Fitqgf9u+PbwvDrXSOwN1bV/f0z4GkG8kOl" +
        "OFR/HoqRtf/WM6Ehydd1XKmj6NrPfMrfyg5q/x7hBXU4rd6wzmFgD1qqcmRBPnf1pnXLX8DzAJCU5HmiHtbZryURAeFcyDV7jk26" +
        "U8vKxzV/NyWSHp5el0NmlCnJENA/LQV01q5OQIiyWE7JN9/V2HpDytgFa3NC5HuIlcZD4g4J9uLvq4pqKyC3cX6wdGY0VNVpOTNe" +
        "6xrrqLmwlIxP5jphNWz0WIycYeUiuGWmkKb5vh2G/XtRH8R/ovi4nhp7MVmY0sVK5zi+mdUjz9PIIpKUdvvvxepf+nL7ZXyz2Mo3" +
        "PHLVFVUgEMbJKc/bEVQIDg2/3KV2S+ErI4ToQwDBs56tc5agoPNGvfGBw2U11USnJF+pwttwSmyv5WdQdXXYxIC7+piFT56rBBkp" +
        "SkfsrRLNZyd3blA1GboapNxmNxYg245CeZjJtLJlpu7veC+Ewtt1t8MZoXgsGG3miYkxila5grOxkdD3dHapYJEzAsMsM+BgN5ZU" +
        "GfPST4ihKAWvkQdhzdkAZiWMhiPtvankOo5/mTY8aQiGpDitXZ0Wk1jEkOd3YS4IB0ttCRK2mBlB3FX1W6QDaUGZiX2g1lWf0etV" +
        "6r96jSplBtI69tygFN0sKq2qPzmHAF/qV9lwLvlvy4HLOlZ3M1zsaffKgz0RnC9epTWCqsJFILqi79d/pEFLs4vczhuGqZ7dEmB9" +
        "oow9PJvFQK7eLQIfabe3GrtCS1qjvdmeMsShYwEkIK5kXZG/WhJW5YPilsV+RCKNEdaFXgncl9XozSQuwqtgcLXmfJVnsEYXMvBh" +
        "7he27lluxdYHrdd4YQMuoNe0NPDBIVkxWLfSLf2pkUW8IIY62BWu46BTcrG/3H9YkRWHpOb5+jsAe1vSzIHMLfHtGcR9g9ZrUUBe" +
        "la2zgvo7b+cIJ6YDWeEd5pquNvxEh84wCK3sZhONAyIUu7fNSb77Ay3MjK37cZutrDKT1g4QxMoVk0I33nyxldkr0QpvoXTvlxFp" +
        "aHptAY1ngeI7YFbqzEBWJGQL4OTNyZvbWw1JTSOIrkV7FkIZhrRNswNo6rZPstN+WSYLBfpD/zFTzCEAbXMUeeMb1yxwl4f9fEU3" +
        "ARd1kR4BEmjjfNxVYP5Td0oSUQZCr9zJRNde+Dsz0r/p8Q50GtF6zuDAdqf/X3KfCvks2rh/WEW2AR/CNCvofBmlbt+D03ExNqqD" +
        "kYgJAZ7u8jrFbpC6WFNUDyBDZVf644lJCczOn1lUtaSBdWwUODxuZsrTZg7zbFLx0xA56BG7EQjaXXabE8VieX1xrAadq12UpOJy" +
        "lgy/AQvvqKDZffK2/98mOP9SiKmkmSc3Wc2B8dP7QuUg6lj3djpl4PYsmbbWD1JW8nRX+Z+uVx36ORS3iBjsmpZbgsm19v75qdKY" +
        "LhHfvWj2fZEoF8/L+e46GXl8M7V8YjnwX+dYdsKce9pBl4RJXwqCvXV3HRiY7D13/jRNccGiyB4qXIANcfUfPDHstwIlgUjdWeNs" +
        "Vspjt9Xk/WJGFHy+RjhCcQ01sWb6jZFCvH95wF37BfpZCzBe8gYv6P8c1OjV8+TnkoUGNSjpOguTEbbO3BLs42TFOZ2BFPiwiZW/" +
        "aqj1D8yEkx75MJTlMwvF9abL/m3lfXkKQ5+M1PKH42VUvUP+qvFPW8XU6QAFvMmeOkIfTYOsgB7svXY5yH1H4hHfcBTny3z6NogS" +
        "lt9xkag3eg6AbtXugbol2CldzzEvZsl4hNeVUt9J/kQfoFDPsyQ6FUACCDQlv+nwilZahzjETsYuXbqp++3Ic354A7tVRJc6AtHf" +
        "bJier11QXIuTox+PSjMPKzo39tfmnpdl8xrcnJQHAByIcKVVGrNU4NhYLgEjRaYq0w70gtcBA+XtSn7mBF2Tyxpb+pMcgrd1LPI8" +
        "Hu9aRupmf2HU4W7rB2bgACCzRDzVWLLUDR8tSUuAHUKqph7fp6NxEEAXLMGtDX6wfwrNnO8VI2zZiC6vrhp1/bKeP3O7LOjkcFpk" +
        "TCSOyhRAkLuFFGHBoJW91yj1Jl1KZw5e1UbByxDdaRS4HVs51KY8XP3CyO4nCCuUQUTgnBCl++uA9348GFiYXqWo/uPVrydonWQH" +
        "V/wI4k8vrcabGZxUuq0/UkzXJ+qeQeog3mXwAH8N8Pfwfts5kO+6JlyYe40Xbzr0wrjBQNi0PCzNDAL1Wu/AgKBzpj2CZ+xLohEo" +
        "77il/uG/C1d2hOe86O1wVFJwBPSv39dm0sDaUmjDQ4MdSQekeKZ3ttLWmk7ljVvesTfCHxZhRz1Vie6TKCEMdhraDFXkpb8RqwmZ" +
        "GNuZc/ejRRlq0X/29xpJxi8MIBtBhRSqZdkCSTtiFUpkqQawZRiFlEjqIEgNh4i+AeHC3/x9cNqFoDON7wRTRZQhiqIjxSUzszEM" +
        "ZZ5zCuXRDNZfEXX7cYtBo+3/VwBDDV36Qjn+QL25biS0m8YacT4KRzAuPXP87426adlaUBCbxdOAE4AhGtefVi3HenZKXEuChc/S" +
        "LSgm9suRzt853oR6kPKnc7TmHI1CZNq1ZVHm3OUkR6y1shWWgMhQnX2LLjijY8H1upwdj2q1dZFRUIFvBSrNAQwsHZa6n5ILDxFs" +
        "TvA8Leevq0vH94R/ipwKaXOhti7ifjyOIEL/a6obAIrsAa273z7KOCTBvSWt1RJqTfiDM/WCTLdlOMnpy3Nj096Bz5rTUe70x67p" +
        "GQsjWAXVTGt6jceooZKtt3Fn7FaX+gn0wbFYh0bZUFFy3eVJXpvbQWq+pQ/MNi31FKV2Ql4Y/zhuQ9beMafUpLVuyecWEvIw8LmO" +
        "BN5zPXUVfYvWWcFOyl7Sb0STDss3DH6J9UpWgds4BvnUTPlICNjXPmqStg+PVWPlwVtRYvJRWeGMmYYmh4Emc5UQDGx2HP2VlhmG" +
        "BuGd18b0hulzvb8jlPhabwj1AiHt0Tb+5JcUHIl3/ZxhEeWKBR0prUSTNwKBfkENeA5acwhQ2mdL9478r/ejFsAgeLVbHmGaHjvO" +
        "nUFWNjb8sIxTv0OuheQ7eIGXrOXnemCQcQSfKhtGzzcAuHgphY0QkPtuuxRSrvnhAFBbqFUIFn8qVE21nvbZAuRUGYpLrRrfQEtf" +
        "yjWfSIrZT27QpTq8soyt8dCtf/63cXu4u24lKjXUAJXE2L3ydZk3BQ5NtOsRrErT/mUTN4ThjcU1Nhnza7yfI2w3GpcZ/AedKUOB" +
        "PoLKAMHzEdx1+4GNxQjPYJvShmtRBEhCtBPf9VXyOmAY7tiEnGTdqBVe5717FDF485S7/j/8VoX3BB4zrlE865BBpqT8o1Enn82J" +
        "/dmPkvVSMfYBbDXLbCQKFcvy8zXwsvP4iRjgPO1mi1TCAO+Y/QjiWZ2YAEEiKZ0M9gkCCBuktqDfoIqO/7KgfIFQAPRyQ6GSpRKQ" +
        "Zi2NfgvETGV2pqtPGGZGbeIjSW3kfL60ERO6CIwxvdbIgyPgt3UIIox9ZDK5/FpYYOCake6+T8+/Fkn/trkdPE4LMHF/xThYK54K" +
        "eJHssJcTmJQPteSbVm9Dxa+/ZevOJAUAwcwSz9gZW03s+boUJHSCh9DJOW76/uYvx7hyp+s0JDjE2u+NKcMBb9+D12NlqcJnQFF1" +
        "6Ku/OvhBegmaYqAI5qnANQVQU42efdll2/kCTO7UKrjKpRU7ZHCgo2sGz85OWKAomcD9OBw0kapfJ8tXT8fhgQ/FRxfrxMUYCmXy" +
        "A00F3Bmp551DgaNqStGvE4SsbEqq5TInIE1LTVurvYqwAB6juWOX6KIK8GrnTYsXuJ3J7Qx5gA6ojsrQnmuvkxhW1rausO0R5o7z" +
        "epQLWLpe/dtiZid6oPck1/1rjJ5fjd7+oPwxAblmyqR9XNxvCcmAXlamPtyBVlHnCGxWgY2A1Dz2DzPSeiEJfnU16ukNErKRSL76" +
        "fzBXmejFRIS7XBeQFcTzVHnB7FmS6UOPpuA+xkuBSfvpvzr7viz10jwjJJLDr1qNqGiaQGgWhecKB5T6ebxwsjEu4J+6CMJvnAD6" +
        "ba5H0arH3yX/S+xe/bN0IHmBIFaO2xVJA0ZHttkoQSSND/w2ZnFqKvMiRzkL/SX1cCEUaAszonz2HKAfa4tzJWPLhxGarLKWhMy9" +
        "E6swfm7VXYOgx4yZzjYxY2DmsMyDUS/glHlqaP9J97eC4LlS7NogLZZ75lmAB9+W+QI3Vp/bMehaRv9dKod4wL4KHuoipiLd9x+v" +
        "ssQpffw1+yw4Gq37dJVuGwASBWna6eYbYuI89itwjyHAjcTnBhMGKRUCagqD+cfVAfspvUgyBXVexW+XW33xGDkrVXr+pHUPB5jY" +
        "RF+yczB+aOxJGYXnz+aNK4qbqtoVTObQmimTyMaaN2NQ22F+VEm6yyzZpMGT63EZwrm0ioKLl9iTy4moUir2/uVi5+8GNzn3NiHr" +
        "HfjfCb9mEcazLVizEn2UQCbLtrqYEuamM0qA3udAI2+HHcSXhHjHuDhhUKY8ljxh/RMqUlmDO81RXr1c1QRz9VXxXa98WA0int5p" +
        "/V+8qSD7JNXhqT56RDPDUNoqk5YKXbVj2BDdu9WZuBOMqiwEb9IEEm/rH4AMjW+QSitiygle83ktrQx7Pg3gsYelFiEZjGU39JnF" +
        "yn2ty9D5xpoP+ly83H/eA/VIXNc4azJnF1FCOLhQOa3rv4b/Du/cU22rGem6RliqNdoHIhYcnaHlmIh6AfQ5uPVeJ2b9KnQMpfVh" +
        "PYmv/j7QD/2qKAiHDCCHmEzLtvq7v+zG3bSRSiDl8kGD+yAcTakGOgn8yWWphO3gE9NsPsLW0LpUCf8kl5/6Vha75zaMp7x1sHWw" +
        "IkIuy1kNMoV6avrQDEsciz3U0vVvj4FEorIF6VO6EIsyAmKB+ZJ7Mg0v/Ofr+/kUyblAfgrRTayhBs+C27wHOREEj5JY+Puq4zpz" +
        "nW0wh2lb1msU+YqAPglxDYvvndPYLHRqIJjjXXDB69XpYjjTYzzUR/N3pOqDW/CnPy9iPgdmNr/KbQ+nHeCrjerdu6qPbfAN0I24" +
        "H3M3s6AC0iARNKBoSE2qmw6A0rJIBq0Qd75VwSLm4ZrPvrisqqtOU9y2YvkQXv/URAmQFmTD55kxyReXpXQLmbee/QRgeBaaYxc5" +
        "rnXEVrM0VzJD+3W8zBTPLEIAi62aZ66bnXxEedH6amEjO3p+FQL6FS70e/g3FGlXRmevMZjv0XmW65hKECYSVIquEsJG2xGTkTw2" +
        "qbLd+kUG5Y8p/HbNm1Yg7r2qrly3qaeA3KQKOubwOJSB6siIdojGe1utPa1wdbGN88oSeMzTBTJTUj4XNsxBzfu1lSTJDsA+a+TQ" +
        "0M8dw9Zr74JIhxquc3KIOkYMw6sxQtqBDIITboIqv+x6kv/fS8p8fAICRh4WJ4GyLD/UbNHmAvOpl/010XAYq6pnxfTCbdVGXjqV" +
        "9OKCZ7WsC5nq/4JnCYefRPSFO5fxSz90P19W1S12hf+b1HkbJGWzI+CZcHHODzSgB7/WzFDZDmGFWAMfQMjmlu7w7WPX1r7ikHFb" +
        "6g7UrzX33ORGn9+cYoNrEDzR9KBp4hD9neR3R2PWoBUCg6zoHDm8/ndURgFmNevX5XGUUjoRRJm5PhS+R+vfo5ZMdkxAU32MROOv" +
        "7hBDl7bWMcXu+urxKQ4+M5fXk5dyus4QfYJUTYQJXaFxkcobMkxON3b6Tbpu7odvDuWRTfQnjoDcobLR97S7TRCk6s/06Wt3mj83" +
        "zktSuoZtgXjXR6Pm3z8kUHylVpqTjbGn1XyVRDAawK6qwasi59j08LbXGGUlLpjs3pIn7efbn9GYEV5CxfbB24wV+Q2VlV5c0Vz1" +
        "EBqKxKpd2CgU7fwIPvXd+e/QHLPceR082O+gzfukFGj/lWXZ2LW8SAw9DQBW4LFyVCboRAiwBJSVmBnl/2va/jaLJFR/VGGfnXDI" +
        "ruhwG7+NqLJjQZn05y+7cDd+M3xEM3F4hffg5muZDkgOwRB5qeYHueW3gJKyWNI5J0FlMOvYUW9BXyb3wE/jRLLTfussS+qUJDOP" +
        "KJ9dB+6oqvTHrUPvf5UN+L48ttCiDYJOzkXVo5Jh64WqMgPfNr4ND9CtikBrIBHEVUcac3zTxroscjI9mWnNdyIOMpKCrov91Tt6" +
        "Qbc1lu9mSpVkvEXy2kgV8Zv+AugYzt8owI5dSlN6Z515AMB2KyaDtQ1Kwbx/6kSpNBpqtvlHIzSWeEpqU+K/BGsJ3YyXdh68iM6v" +
        "poAzPooINyasPT2GV0ZWlJIeJtdMH8E0lPSjRT4D3YyI6ylicygXEbN2X1XlaxscektsTw84mi49v9QXVEmlb7M8kGR4GGyg6Q4J" +
        "cOoMkGUU9lD9pN9wZm/9L+5jhKTnRZ8/o8lBRcm46HZ8ACNHTAGfEkqA3l9cBra1nPjlAW9Eb3D/A9CyeL5sGXhudVW9C+/ckRA2" +
        "an8JsxsuUCCTHlKMumReqIodLhHo8lWbwphogyfRNiA0DEm9e98CX3xYUfmvw9guS4B84wzfqB9mjtZM4fmtuYu0gk5UoN311lBi" +
        "4x9tyr5ZSKAK+FOUO4iImhVeSO77OiY4hA3cj67BPpYIONsdlC9CjTAO6cgBDckAneEzQjRIZdOGQyJrCZqzvkG7e+TAsorBm/tI" +
        "AJPxYZT+t6ia3ViOvBSLFHsXkdi1yrpp+ZoMJruBiJpC8lWWKDhNhWSt72LUfR2fKXcszdyrqduJb2A80UJHsyyjPHBirP8NSdcc" +
        "V/AjWalvt1nQU3DQ942kuHGWGFjqJpDn9YjMuyaSi5H6BuEUAvz9szZlzlbwo1Q+ZBITpeRbpL+18gnRi/jbEAMLP9a2NV5KOrXC" +
        "v3nO5vIdRLPslMQHSvic0ga1KeOmH2YXc7LFUcUuLH1pB+ZL8FMXjhBTiOr1Q8ePlOYlGuJamkjfMA4j0ZOZ4N2fpciB9Mp5zJJH" +
        "s7ftmtuHauTL/vSsXij6607ctA7LfMwacBgO6f1dag7o6lidNmaHB2uZShqBem16vCa8UviL4WVNxtKO2B3tkT89FrDUKQP2OIUi" +
        "9oqMhGgigHSb2r98xD/l5NKVDY5Rj+0HCDTm+mYeB3O+V/eX0xZJxNp5hOopEVnO5xzy9EmzqCP1GQm0oAV2S060c3lQN8ArH/PT" +
        "EjEHjjnzWf0sRHFCvCNvsua7rxlMxnglbUDI81w+lUc6ne2UuT+Bhc/SHwxSTvCtMRIZYjE/CICFBaXGyKLGHWFG0VfEd7feKGXt" +
        "/pDmgC735WbFLNsp/z1YuDTipmWA0TkecYKlfkZcGHGRt246W3z6IIsa6vsaCW8kMbmBWVcPik7xpKPGzcxjzCSxy1JBPZta+o2J" +
        "Y7liqto8MeUM71wHYR1miLgTqLxqaI9YYcK9PSzkEfGr1tIG98jfuJRtWgQYf7e086lc9gFhqi3iMTjamIBGsJ4amk4nBwhB5I54" +
        "SHq2NBBvsb3SVjvZjQ+UFzhM1oldRB7yyn0ZV16yk25am9rFYwIb1UlTJUoQ7P8yY9+dRAZpzjL/VCWKYMYHHu1kxwEIuPX4IpBs" +
        "QY62WyRonALdLZzNFK2RU4sODN/3Xclz4qKnf7XPlGuiVQIRvMMPL8KLVIWtbW4UUlZV05rvAchgZvfuIMCiIbx6vPbtBATPAX1i" +
        "i3GawetY9NA3c+iaarxjoG9E+gYzudI0FCrgyFXC+RsCc8GiROPeIpSbeb0pvBJ1xQ6StKO9LwWb5GXEzcXkscehXeLgv1jz3UjV" +
        "dX87diSqMeQaykgsUHR1DD988kF1napmxS9jUyqtXo3Owisx9Ez9GWSQDDp1RGCAkmrLjIiQ2RNSjNpB2SZgug9QKdVSSYNvi6g5" +
        "3+YaMHgFEEVm3yq08ZaLH2/HOt5V7IX4BnMoSqPePSUfwepYhD0l1aLrUxZdPF1Lj1wXPOps1U5JeEM3im3IVJNDqwCzOPMw3bsS" +
        "i9fdhSAMVDjlslxHIDQlEa+bHCghjZeixMuRJIsKMRpRw706fm0iDtMkXS63t5ftqAV0waz56b4dUxALKEHJjr1ES8l0jiB9aNn0" +
        "QMwQPg3Eh7Btb59FOpVHnOpeMpJavrR2ZLZFZWm9OXD+58SnUt9VOOTaCQMxiOze9ler/GfP0FFNtYUTn4tHZBPY+GIWHW8Npqpi" +
        "UAPC4mV4wFgAdogXxX8adpkCImy0sP0tTTqJn/HN79DOSKwQBKxXLwuU8OmckJcUzSy/+VMDxZylQ/pVHu98Loq7WDZZ2DEZOClu" +
        "9IMB5RJZ73adsK8vhU5bfCzpj8fNAMfkh/zbBRTTMEDjIc3/4B+gDmQ6ekhiMoa4tJAKEFKaM0mR2HKynZ5pkHt1dK2TvX1cSACN" +
        "6DJjBmVGeMNEhsH3tYoO7EUbAFsmhmdBpr731pSlhOHEq1pGeMigy9IQxoHU/LrMlKDmY9tus3fPhdYaq0iSxd0Z6md1LthAlWKQ" +
        "Odwpj5BzXrqJuvujwHiFmYsMKAX1U3vyXbekRKYXaN0KVNO7um2oWkKNxh1ZqtJHdG+kpqZ9fzRyO8h/xDfpErdxkij8ApP6bDLv" +
        "qsdgfvN9Lxl8tDaNFn//fhcY1na5DGQTicZAOMjqVGfoHwPqWzQjpJH3j8BYCjqAlpgfbRKESyj1kmKBlnWwURZBsZY6Qr5amISt" +
        "RVKoqh9GUhA8G1mJVvZ2WspoCIwl5koEbo+7tCFsHwBAq7jvz/NiUpfNqr6rJ+aZAr57TeNAchBL4SA01PO+MkdwgPcrKoQYiFhE" +
        "JuhbQppLiYLA1lKBBqisxFiSIB1uxsKmnZ29/Usp7QQjhblT/FpoIlUyEbCxxM3w0EkQ6IqQlKw6BMIEWiz4a69k6e+Ulw3Wsn2A" +
        "q6KtG3E7FHu92rDK3wfuWpONC/RWvLCRmTEAXQqEbYjY7BZZEmm5VCIh4NoJswaeQmP95vfNm2453zE5ZnP99QM69RixZOgUdmjP" +
        "8XbJTF5/re3IHpG3x2Z3rXhu++pogmVNIOW02M8BzkFCgea6hK4v1U7g38XeNgG6khQBnV3SRs/vGmYYYta9dOtaSPQSZSbd4FQR" +
        "gp35IITy83Mau///hl6gK/NNDS962VySbDPM1Y6bvqvsO2r1qZ87z4gSzdxC0pX/UZ8vQCmw83flwjb1CAReMuQOghgJTinxzVXL" +
        "aICdcFn0PaH7aaGWyWVvCfT8eMHJ6fztCMzoxEd2nzMwvbmyO+jmvkKPshTtfwb6y/fKBvorLXAwzC8wIrhrSuZth+Tjb2SnjlMG" +
        "l/O6gcRM/0d5Ay41E6GeJokeIVEcyR+EbQpKtssffMXVIEBmB2JvhA70vN9JI92cquIh/AbG+J9pGW+tuxKazk4KF5CZqGaHLS3z" +
        "AWTctJonLGxbSjYU02mUq5u29FNSTAda5KQcdxeYiKCtAXi3XKr/HnjXfbnsMQgnobNNHO0ukb5Z6syZalK+pCOj22zv7zbN7HV8" +
        "bm6kMPOJqM8rx+aPisXXpXtx2zaC17xN709w6XJlzVOCmHVZr92tc3//nMSXOJqaosYH8ZUCflGszokrqHofKhYM5SgAm+W14dAH" +
        "/jNytsvbSmdOd5TUmDipnMJT2vMaYhdfAZYF4IIpxswzBvZ2O712CciEVYr0YCDgSp5+524+OJTk4GMKQuCcfqKfckDz4uJ/SbOb" +
        "ueXn+sV8H1WH+O40vki6HHyhZY4TcJw8qA+GljUvmlhd5NTYqJ4cotVdu0gfQBPOfAcHkW7eKV+k9j2LXx7at2G4o51d13+GyU8e" +
        "X3zynl/cBo2oLhTvU2dX0xFzpxIhatMaU+d30B8lWxCde/S/cy2VGjXc29ZWUg==" +
        "";
    public const string PtTestSha256 = "86bb1b61ad2b14604cdcddd4a8e9dd43fc36652a3dd35daf57697cb1c8e51245";
}


// DMT3 .pt (PTFF) converter - core algorithm
// Ported from pt_cipher.py (MT19937 + feedback TEA), which was
// cross-verified against samnyan/DMTQ-Tools PtCipher (no code copied).
// C# 5 compatible (.NET Framework v4.0 csc / PowerShell Add-Type).

static class PtCore
{
    // ------------------------------------------------------------ MT19937

    class MT
    {
        readonly uint[] mt = new uint[624];
        int idx = 624;

        public MT(uint[] key)
        {
            InitGenrand(19650218);
            InitByArray(key);
        }

        void InitGenrand(uint s)
        {
            mt[0] = s;
            for (int i = 1; i < 624; i++)
                mt[i] = 1812433253u * (mt[i - 1] ^ (mt[i - 1] >> 30)) + (uint)i;
            idx = 624;
        }

        void InitByArray(uint[] key)
        {
            int i = 1, j = 0;
            int k = Math.Max(624, key.Length);
            for (; k > 0; k--)
            {
                mt[i] = (mt[i] ^ ((mt[i - 1] ^ (mt[i - 1] >> 30)) * 1664525u)) + key[j] + (uint)j;
                i++;
                j++;
                if (i >= 624) { mt[0] = mt[623]; i = 1; }
                if (j >= key.Length) j = 0;
            }
            for (k = 623; k > 0; k--)
            {
                mt[i] = (mt[i] ^ ((mt[i - 1] ^ (mt[i - 1] >> 30)) * 1566083941u)) - (uint)i;
                i++;
                if (i >= 624) { mt[0] = mt[623]; i = 1; }
            }
            mt[0] = 0x80000000u;
        }

        public uint Genrand()
        {
            if (idx >= 624)
            {
                for (int i = 0; i < 227; i++)
                {
                    uint y = (mt[i] & 0x80000000u) | (mt[i + 1] & 0x7FFFFFFFu);
                    mt[i] = mt[i + 397] ^ (y >> 1) ^ ((y & 1) != 0 ? 0x9908B0DFu : 0u);
                }
                for (int i = 227; i < 623; i++)
                {
                    uint y = (mt[i] & 0x80000000u) | (mt[i + 1] & 0x7FFFFFFFu);
                    mt[i] = mt[i - 227] ^ (y >> 1) ^ ((y & 1) != 0 ? 0x9908B0DFu : 0u);
                }
                {
                    uint y = (mt[623] & 0x80000000u) | (mt[0] & 0x7FFFFFFFu);
                    mt[623] = mt[396] ^ (y >> 1) ^ ((y & 1) != 0 ? 0x9908B0DFu : 0u);
                }
                idx = 0;
            }
            uint r = mt[idx++];
            r ^= r >> 11;
            r ^= (r << 7) & 0x9D2C5680u;
            r ^= (r << 15) & 0xEFC60000u;
            r ^= r >> 18;
            return r;
        }
    }

    // ------------------------------------------------------------- TEA
    // 32 rounds, delta 0x9E3779B9, sum incremented first; key = (k0,k1) twice.

    static void TeaEncryptBlock(ref uint v0, ref uint v1, uint k0, uint k1)
    {
        uint s = 0;
        for (int i = 0; i < 32; i++)
        {
            s += 0x9E3779B9u;
            v0 += ((v1 << 4) + k0) ^ (v1 + s) ^ ((v1 >> 5) + k1);
            v1 += ((v0 << 4) + k0) ^ (v0 + s) ^ ((v0 >> 5) + k1);
        }
    }

    // ----------------------------------------------------------- CRC32
    // standard CRC-32 (reflected poly 0xEDB88320, init/xorout 0xFFFFFFFF)
    // == zlib.crc32

    static uint[] _crcTab;

    static uint Crc32(byte[] data, int off, int len)
    {
        if (_crcTab == null)
        {
            _crcTab = new uint[256];
            for (uint n = 0; n < 256; n++)
            {
                uint v = n;
                for (int b = 0; b < 8; b++)
                    v = (v & 1) != 0 ? (v >> 1) ^ 0xEDB88320u : v >> 1;
                _crcTab[n] = v;
            }
        }
        uint crc = 0xFFFFFFFFu;
        for (int i = off; i < off + len; i++)
            crc = (crc >> 8) ^ _crcTab[(crc ^ data[i]) & 0xFF];
        return ~crc;
    }

    // ------------------------------------------------------------ cipher

    const int HeaderLen = 0x18;   // plaintext header

    public static bool IsPtff(byte[] data)
    {
        return data != null && data.Length >= 4 &&
               data[0] == 'P' && data[1] == 'T' && data[2] == 'F' && data[3] == 'F';
    }

    // heuristic: decrypted files have an ASCII sound table right after the
    // header; encrypted bytes look random (~50% high-bit). Used to skip files
    // that are already decrypted (re-running the cipher would garble them).
    public static bool LooksDecrypted(byte[] data)
    {
        if (!IsPtff(data)) return false;
        int n = Math.Min(64, data.Length - HeaderLen - 4);
        if (n <= 0) return true;
        int printable = 0;
        for (int i = HeaderLen + 4; i < HeaderLen + 4 + n; i++)
        {
            byte b = data[i];
            if (b == 0 || (b >= 32 && b < 127)) printable++;
        }
        return printable * 10 >= n * 7;
    }

    // decrypt whole file in place semantics: header stays, body decrypted.
    public static byte[] DecryptFile(byte[] data)
    {
        if (data.Length <= HeaderLen) return data;
        // h1 = crc32(header), h2 = sum(header)   [pt_cipher.py]
        uint h1 = Crc32(data, 0, HeaderLen);
        uint h2 = 0;
        for (int i = 0; i < HeaderLen; i++) h2 += data[i];
        uint[] keyU32 = new uint[6];
        for (int i = 0; i < 6; i++)
            keyU32[i] = BitConverter.ToUInt32(data, i * 4);
        MT mt = new MT(keyU32);
        uint k10 = h2, k11 = h1;                 // key1 feedback block
        uint kb0 = mt.Genrand(), kb1 = mt.Genrand();

        byte[] outp = new byte[data.Length];
        Array.Copy(data, outp, data.Length);
        int n = data.Length;
        int i2 = HeaderLen;
        while (i2 < n)
        {
            byte[] key1 = BitConverter.GetBytes(k10);
            byte[] key1b = BitConverter.GetBytes(k11);
            byte[] key2 = BitConverter.GetBytes(kb0);
            byte[] key2b = BitConverter.GetBytes(kb1);
            byte[] pt = new byte[8];
            for (int k = 0; k < 8 && i2 < n; k++, i2++)
            {
                byte kk = (byte)((k < 4 ? key1[k] : key1b[k - 4]) ^ (k < 4 ? key2[k] : key2b[k - 4]));
                outp[i2] = (byte)(outp[i2] ^ kk);
                pt[k] = outp[i2];
            }
            uint pt0 = BitConverter.ToUInt32(pt, 0);
            uint pt1 = BitConverter.ToUInt32(pt, 4);
            TeaEncryptBlock(ref k10, ref k11, pt0, pt1);
            kb0 = mt.Genrand();
            kb1 = mt.Genrand();
        }
        return outp;
    }

    // ------------------------------------------------------------ selftest

    public static string SelfTest()
    {
        byte[] raw = Convert.FromBase64String(EmbeddedData.PtTestRawB64);
        byte[] dec = DecryptFile(raw);
        var sha = System.Security.Cryptography.SHA256.Create();
        byte[] hash = sha.ComputeHash(dec);
        StringBuilder sb = new StringBuilder();
        foreach (byte b in hash) sb.Append(b.ToString("x2"));
        if (sb.ToString() != EmbeddedData.PtTestSha256)
            return "PT 解密自检失败: 输出哈希不符";
        if (LooksDecrypted(raw))
            return "PT 自检失败: 密文样本被误判为明文";
        if (!LooksDecrypted(dec))
            return "PT 自检失败: 解密结果未通过明文特征检查";
        return null;   // OK
    }
}


// DMT3 .pt (PTFF) converter - WinForms GUI (double-click mode)

static class PtGui
{
    public static void Run()
    {
        Application.EnableVisualStyles();
        Application.SetCompatibleTextRenderingDefault(false);
        Application.Run(new MainForm());
    }

    class MainForm : Form
    {
        ListBox lst;
        TextBox txtOut;
        CheckBox chkInPlace;
        Button btnAddFiles, btnAddDir, btnRemove, btnClear, btnBrowse, btnStart, btnCancel;
        ProgressBar bar;
        Label lblStatus;
        TextBox log;
        BackgroundWorker bw;
        List<string> resultLines;

        public MainForm()
        {
            Text = "DMT3 .pt 谱面转换器";
            Width = 720;
            Height = 560;
            MinimumSize = new Size(560, 460);
            StartPosition = FormStartPosition.Manual;
            var wa = Screen.PrimaryScreen.WorkingArea;
            Location = new Point(wa.Left + Math.Max(0, (wa.Width - Width) / 2),
                                 wa.Top + Math.Max(0, (wa.Height - Height) / 2));
            TopMost = true;
            Shown += delegate { TopMost = false; Activate(); };

            var tip = new Label();
            tip.Text = "把 .pt 文件或装着 pt 的文件夹拖进下面列表（也可用按钮添加）：";
            tip.Dock = DockStyle.Top;
            tip.Height = 22;
            tip.Padding = new Padding(6, 4, 0, 0);

            lst = new ListBox();
            lst.Dock = DockStyle.Top;
            lst.Height = 150;
            lst.AllowDrop = true;
            lst.HorizontalScrollbar = true;
            lst.DragEnter += delegate (object s, DragEventArgs e)
            {
                if (e.Data.GetDataPresent(DataFormats.FileDrop))
                    e.Effect = DragDropEffects.Copy;
            };
            lst.DragDrop += delegate (object s, DragEventArgs e)
            {
                AddPaths((string[])e.Data.GetData(DataFormats.FileDrop));
            };

            var pnlBtns = new FlowLayoutPanel();
            pnlBtns.Dock = DockStyle.Top;
            pnlBtns.Height = 34;
            btnAddFiles = new Button(); btnAddFiles.Text = "添加 pt 文件";
            btnAddDir = new Button(); btnAddDir.Text = "添加文件夹";
            btnRemove = new Button(); btnRemove.Text = "移除选中";
            btnClear = new Button(); btnClear.Text = "清空";
            foreach (Button b in new[] { btnAddFiles, btnAddDir, btnRemove, btnClear })
            {
                b.AutoSize = true;
                pnlBtns.Controls.Add(b);
            }
            btnAddFiles.Click += delegate
            {
                var d = new OpenFileDialog();
                d.Filter = "DMT3 谱面文件 (*.pt)|*.pt|所有文件 (*.*)|*.*";
                d.Multiselect = true;
                if (d.ShowDialog(this) == DialogResult.OK) AddPaths(d.FileNames);
            };
            btnAddDir.Click += delegate
            {
                var d = new FolderBrowserDialog();
                if (d.ShowDialog(this) == DialogResult.OK) AddPaths(new[] { d.SelectedPath });
            };
            btnRemove.Click += delegate
            {
                for (int i = lst.SelectedIndices.Count - 1; i >= 0; i--)
                    lst.Items.RemoveAt(lst.SelectedIndices[i]);
            };
            btnClear.Click += delegate { lst.Items.Clear(); };

            var pnlOpt = new FlowLayoutPanel();
            pnlOpt.Dock = DockStyle.Top;
            pnlOpt.Height = 30;
            chkInPlace = new CheckBox();
            chkInPlace.Text = "覆盖解密前的 pt（不可逆）";
            chkInPlace.AutoSize = true;
            chkInPlace.Margin = new Padding(8, 6, 0, 0);
            chkInPlace.CheckedChanged += delegate
            {
                bool off = chkInPlace.Checked;
                txtOut.Enabled = !off;
                btnBrowse.Enabled = !off;
            };
            pnlOpt.Controls.Add(chkInPlace);

            var pnlOut = new Panel();
            pnlOut.Dock = DockStyle.Top;
            pnlOut.Height = 32;
            var lblOut = new Label();
            lblOut.Text = "输出目录:";
            lblOut.AutoSize = true;
            txtOut = new TextBox();
            txtOut.Text = "";
            txtOut.Anchor = AnchorStyles.Left | AnchorStyles.Right;
            btnBrowse = new Button(); btnBrowse.Text = "浏览...";
            btnBrowse.AutoSize = true;
            btnBrowse.Click += delegate
            {
                var d = new FolderBrowserDialog();
                if (txtOut.Text.Length > 0) d.SelectedPath = txtOut.Text;
                if (d.ShowDialog(this) == DialogResult.OK) txtOut.Text = d.SelectedPath;
            };
            pnlOut.Controls.Add(lblOut);
            pnlOut.Controls.Add(txtOut);
            pnlOut.Controls.Add(btnBrowse);
            pnlOut.Resize += delegate { LayoutOutPanel(pnlOut, lblOut, txtOut, btnBrowse); };
            LayoutOutPanel(pnlOut, lblOut, txtOut, btnBrowse);

            var pnlRun = new FlowLayoutPanel();
            pnlRun.Dock = DockStyle.Top;
            pnlRun.Height = 36;
            btnStart = new Button(); btnStart.Text = "开始转换"; btnStart.AutoSize = true;
            btnCancel = new Button(); btnCancel.Text = "取消"; btnCancel.AutoSize = true; btnCancel.Enabled = false;
            bar = new ProgressBar(); bar.Width = 300; bar.Height = 22; bar.Margin = new Padding(12, 6, 0, 0);
            pnlRun.Controls.Add(btnStart);
            pnlRun.Controls.Add(btnCancel);
            pnlRun.Controls.Add(bar);

            lblStatus = new Label();
            lblStatus.Dock = DockStyle.Top;
            lblStatus.Height = 20;
            lblStatus.Padding = new Padding(6, 2, 0, 0);

            log = new TextBox();
            log.Multiline = true;
            log.ReadOnly = true;
            log.ScrollBars = ScrollBars.Vertical;
            log.Dock = DockStyle.Fill;
            log.Font = new Font("Consolas", 9f);

            var notice = new Label();
            notice.Text = Program.FreeNotice;
            notice.Dock = DockStyle.Bottom;
            notice.ForeColor = Color.DarkRed;
            notice.Height = 22;
            notice.TextAlign = ContentAlignment.MiddleCenter;

            Controls.Add(notice);
            Controls.Add(log);
            Controls.Add(lblStatus);
            Controls.Add(pnlRun);
            Controls.Add(pnlOut);
            Controls.Add(pnlOpt);
            Controls.Add(pnlBtns);
            Controls.Add(lst);
            Controls.Add(tip);

            bw = new BackgroundWorker();
            bw.WorkerReportsProgress = true;
            bw.WorkerSupportsCancellation = true;
            bw.DoWork += DoConvert;
            bw.ProgressChanged += delegate (object s, ProgressChangedEventArgs e)
            {
                bar.Value = Math.Min(bar.Maximum, Math.Max(bar.Minimum, e.ProgressPercentage));
                string msg = e.UserState as string;
                if (msg != null) lblStatus.Text = msg;
            };
            bw.RunWorkerCompleted += delegate
            {
                btnStart.Enabled = true;
                btnCancel.Enabled = false;
                foreach (string ln in resultLines) AppendLog(ln);
                AppendLog("—— 结束 ——");
            };

            btnStart.Click += delegate
            {
                if (lst.Items.Count == 0)
                {
                    MessageBox.Show(this, "请先拖入或添加要转换的 pt / 文件夹。", "提示",
                        MessageBoxButtons.OK, MessageBoxIcon.Information);
                    return;
                }
                if (!chkInPlace.Checked && txtOut.Text.Trim().Length == 0)
                {
                    MessageBox.Show(this, "请设置输出目录（或勾选\"覆盖解密前的 pt\"）。", "提示",
                        MessageBoxButtons.OK, MessageBoxIcon.Information);
                    return;
                }
                if (chkInPlace.Checked)
                {
                    var dr = MessageBox.Show(this,
                        "覆盖模式会直接改写原始 pt 文件，且不可恢复（该加密不可逆）。\n确定继续吗？",
                        "确认覆盖", MessageBoxButtons.YesNo, MessageBoxIcon.Warning);
                    if (dr != DialogResult.Yes) return;
                }
                List<string> inputs = new List<string>();
                foreach (object it in lst.Items) inputs.Add(it.ToString());
                log.Clear();
                lblStatus.Text = "正在扫描...";
                btnStart.Enabled = false;
                btnCancel.Enabled = true;
                resultLines = new List<string>();
                bw.RunWorkerAsync(new object[] { inputs, txtOut.Text.Trim(), chkInPlace.Checked });
            };
            btnCancel.Click += delegate { bw.CancelAsync(); };
        }

        static void LayoutOutPanel(Panel p, Label l, TextBox t, Button b)
        {
            l.Left = 6; l.Top = 8;
            b.Left = p.Width - b.Width - 8; b.Top = 5;
            t.Left = l.Right + 6; t.Top = 6;
            t.Width = Math.Max(80, b.Left - t.Left - 8);
        }

        void AddPaths(IEnumerable<string> paths)
        {
            foreach (string p in paths)
            {
                if (String.IsNullOrEmpty(p)) continue;
                bool dup = false;
                foreach (object it in lst.Items)
                    if (String.Equals(it.ToString(), p, StringComparison.OrdinalIgnoreCase)) { dup = true; break; }
                if (!dup) lst.Items.Add(p);
            }
        }

        void AppendLog(string s)
        {
            log.AppendText(s + Environment.NewLine);
        }

        void DoConvert(object sender, DoWorkEventArgs e)
        {
            object[] pa = (object[])e.Argument;
            List<string> inputs = (List<string>)pa[0];
            string outDir = (string)pa[1];
            bool inPlace = (bool)pa[2];

            List<Program.PtJob> jobs = Program.CollectPts(inputs,
                delegate (string m) { resultLines.Add(m); });
            if (jobs.Count == 0)
            {
                resultLines.Add("没有找到任何 .pt 文件。");
                return;
            }
            if (inPlace)
                resultLines.Add("覆盖模式：原地覆盖解密前的 pt（不可逆）");
            else
            {
                Directory.CreateDirectory(outDir);
                resultLines.Add("输出目录: " + outDir);
            }
            resultLines.Add("共 " + jobs.Count + " 个 pt");
            var sw = System.Diagnostics.Stopwatch.StartNew();
            Program.ConvertResult r = Program.ConvertAll(jobs, outDir, inPlace,
                delegate (string m) { resultLines.Add(m); },
                delegate (int done, int total, string cur)
                {
                    int pct = total > 0 ? (int)(done * 100.0 / total) : 0;
                    bw.ReportProgress(pct, done + "/" + total + "  " + Path.GetFileName(cur));
                },
                delegate { return bw.CancellationPending; });
            foreach (string m in r.Messages) resultLines.Add(m);
            resultLines.Add("完成: 解密 " + r.Ok + " 个, 原样复制明文 " + r.Copied + " 个, 跳过 " +
                            r.Skipped + " 个, 失败 " + r.Failed + " 个, 耗时 " + (sw.ElapsedMilliseconds / 1000) + "s");
        }
    }
}


// DMT3 .pt (PTFF) converter - CLI entry

public static class Program
{
    public class PtJob
    {
        public string Src;
        public string Rel;   // relative path under output root (unused in in-place mode)
    }

    public class ConvertResult
    {
        public int Ok, Copied, Skipped, Failed;
        public List<string> Messages = new List<string>();
    }

    [STAThread]
    public static int Main(string[] args)
    {
        string st = PtCore.SelfTest();
        if (st != null)
        {
            Console.WriteLine("[自检失败] " + st);
            if (args.Length == 0)
                System.Windows.Forms.MessageBox.Show(st, "DMT3 谱面转换器 - 自检失败",
                    System.Windows.Forms.MessageBoxButtons.OK,
                    System.Windows.Forms.MessageBoxIcon.Error);
            return 2;
        }

        if (args.Length == 0)
        {
            PtGui.Run();
            return 0;
        }
        return RunCli(args);
    }

    public const string FreeNotice = "本程序开源、免费。如果您是付费得到这个程序的，请立即退款并举报卖家。";

    static void Usage()
    {
        Console.WriteLine(FreeNotice);
        Console.WriteLine();
        Console.WriteLine("DMT3 .pt 谱面转换器（解密 PTFF）");
        Console.WriteLine("用法: DMT3谱面转换器.bat <pt文件或文件夹...> [-o 输出目录] [-i]");
        Console.WriteLine("  -i, --in-place   覆盖解密前的 pt（不可逆），不需要输出目录");
        Console.WriteLine("  不带参数运行时弹出图形界面。");
    }

    static int RunCli(string[] args)
    {
        List<string> inputs = new List<string>();
        string outDir = null;
        bool inPlace = false;
        for (int i = 0; i < args.Length; i++)
        {
            string a = args[i];
            if (a == "-o" || a == "--output")
            {
                if (++i >= args.Length) { Console.WriteLine("!! -o 缺少参数"); return 2; }
                outDir = args[i];
            }
            else if (a == "-i" || a == "--in-place")
            {
                inPlace = true;
            }
            else if (a == "-h" || a == "--help" || a == "/?")
            {
                Usage();
                return 0;
            }
            else inputs.Add(a);
        }
        if (inputs.Count == 0) { Usage(); return 2; }

        List<PtJob> jobs = CollectPts(inputs, delegate (string m) { Console.WriteLine(m); });
        if (jobs.Count == 0) { Console.WriteLine("!! 没有找到任何 .pt 文件"); return 1; }

        Console.WriteLine(FreeNotice);
        Console.WriteLine();
        if (!inPlace)
        {
            if (outDir == null) outDir = Path.Combine(Directory.GetCurrentDirectory(), "DMT3_pt_decrypted");
            Directory.CreateDirectory(outDir);
            Console.WriteLine("输出目录: " + outDir);
        }
        else
        {
            Console.WriteLine("!! 覆盖模式：将原地覆盖解密前的 pt（不可逆）");
        }
        Console.WriteLine("待转换: " + jobs.Count + " 个 pt");

        ConvertResult r = ConvertAll(jobs, outDir, inPlace,
            delegate (string m) { Console.WriteLine(m); },
            delegate (int done, int total, string cur)
            {
                if (done == total || done % 100 == 0)
                    Console.Write("\r  " + done + "/" + total + "    ");
            },
            null);
        Console.WriteLine();
        Console.WriteLine("完成: 解密 " + r.Ok + " 个, 原样复制明文 " + r.Copied + " 个, 跳过 " +
                          r.Skipped + " 个, 失败 " + r.Failed + " 个");
        return r.Failed > 0 ? 1 : 0;
    }

    // collect .pt files; rel path preserved under each dragged folder,
    // loose files go to output root (collisions get parent-dir prefix / counter)
    public static List<PtJob> CollectPts(List<string> inputs, Action<string> log)
    {
        List<PtJob> jobs = new List<PtJob>();
        var seenSrc = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var usedRel = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (string inp in inputs)
        {
            string s = inp.Trim().Trim('"');
            if (s.Length == 0) continue;
            try
            {
                if (File.Exists(s))
                {
                    if (!s.EndsWith(".pt", StringComparison.OrdinalIgnoreCase)) continue;
                    if (!seenSrc.Add(s)) continue;
                    string rel = Path.GetFileName(s);
                    if (!usedRel.Add(rel))
                    {
                        string alt = Path.GetFileName(Path.GetDirectoryName(s)) + "_" + rel;
                        int n = 2;
                        string tryRel = alt;
                        while (!usedRel.Add(tryRel))
                        {
                            string baseR = Path.GetFileNameWithoutExtension(alt);
                            tryRel = baseR + "_" + n + ".pt";
                            n++;
                        }
                        rel = tryRel;
                        if (log != null) log("  重名: " + s + " -> 输出为 " + rel);
                    }
                    jobs.Add(new PtJob { Src = s, Rel = rel });
                }
                else if (Directory.Exists(s))
                {
                    foreach (string f in Directory.GetFiles(s, "*.pt", SearchOption.AllDirectories))
                    {
                        if (!seenSrc.Add(f)) continue;
                        string rel = f.Substring(s.Length).TrimStart('\\', '/');
                        usedRel.Add(rel);
                        jobs.Add(new PtJob { Src = f, Rel = rel });
                    }
                }
                else if (log != null) log("!! 路径不存在: " + s);
            }
            catch (Exception ex)
            {
                if (log != null) log("!! 无法访问 " + s + ": " + ex.Message);
            }
        }
        return jobs;
    }

    public static ConvertResult ConvertAll(List<PtJob> jobs, string outDir, bool inPlace,
                                           Action<string> log,
                                           PakProgressFn progress, Func<bool> cancelCheck)
    {
        ConvertResult res = new ConvertResult();
        for (int i = 0; i < jobs.Count; i++)
        {
            if (cancelCheck != null && cancelCheck()) break;
            PtJob job = jobs[i];
            try
            {
                byte[] data = File.ReadAllBytes(job.Src);
                if (!PtCore.IsPtff(data))
                {
                    res.Skipped++;
                    res.Messages.Add("跳过（不是 PTFF）: " + job.Src);
                }
                else if (PtCore.LooksDecrypted(data))
                {
                    // DMT3 的 pak 里混有少量本就未加密的 pt（tutorial/demo 那几个）
                    if (inPlace)
                    {
                        res.Skipped++;
                        res.Messages.Add("跳过（已是明文）: " + job.Src);
                    }
                    else
                    {
                        string dst2 = Path.Combine(outDir, job.Rel);
                        string dir2 = Path.GetDirectoryName(dst2);
                        if (dir2.Length > 0) Directory.CreateDirectory(dir2);
                        File.WriteAllBytes(dst2, data);
                        res.Copied++;
                        res.Messages.Add("已是明文，原样复制: " + job.Src);
                    }
                }
                else
                {
                    byte[] dec = PtCore.DecryptFile(data);
                    string dst = inPlace ? job.Src : Path.Combine(outDir, job.Rel);
                    string dir = Path.GetDirectoryName(dst);
                    if (dir.Length > 0) Directory.CreateDirectory(dir);
                    File.WriteAllBytes(dst, dec);
                    res.Ok++;
                }
            }
            catch (Exception ex)
            {
                res.Failed++;
                res.Messages.Add("失败: " + job.Src + " -> " + ex.Message);
            }
            if (progress != null) progress(i + 1, jobs.Count, job.Src);
        }
        return res;
    }

    public delegate void PakProgressFn(int done, int total, string currentName);
}

'@

$cp = New-Object System.CodeDom.Compiler.CompilerParameters
$cp.GenerateInMemory = $true
$cp.GenerateExecutable = $false
$cp.CompilerOptions = '/optimize+'
[void]$cp.ReferencedAssemblies.Add('System.dll')
[void]$cp.ReferencedAssemblies.Add('System.Core.dll')
[void]$cp.ReferencedAssemblies.Add('System.Windows.Forms.dll')
[void]$cp.ReferencedAssemblies.Add('System.Drawing.dll')
try {
    Add-Type -TypeDefinition $cs -CompilerParameters $cp -ErrorAction Stop
} catch {
    Write-Host "编译失败: $_"
    if ($global:__cliArgs.Count -eq 0) { [void][System.Reflection.Assembly]::LoadWithPartialName('System.Windows.Forms'); [void][System.Windows.Forms.MessageBox]::Show("编译失败: $_", 'DMT3 谱面转换器') }
    exit 2
}
exit [Program]::Main($global:__cliArgs)

# ---------------------------------------------------------------
# 本程序开源、免费。
# 如果您是付费得到这个程序的，请立即退款并举报卖家。
# ---------------------------------------------------------------
